SRC= 
LIBS= 
REST= README GFADD.bash plot.bash makefile
DATADIRS=javacombined_inout_pagerank.txt
GRID= 32
ALL= $(SRC) $(LIBS) $(REST) $(DATADIRS) $(GRID)
demo: 
	bash GFADD.bash $(DATADIRS) $(GRID)

clean:
	\rm -rf gfadd
